version: '3.3'

services:
  deep_model:
    build: ./app_deep_model
    hostname: deep_model
    environment:
      - DEEP_MODEL_APP=http://127.0.0.1:5051
      - REDIS_HOST=redis-server
      - HOST_DB=mysql
    ports:
      - 5051:5051  # host:container
    depends_on:
      - mysql
      - redis-server
    networks:
      - app-network

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis-server:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: